version: "3.8"

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./src/js:/usr/share/nginx/html/js
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  browser-sync:
    image: node:14-alpine 
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install -g browser-sync && browser-sync start --config bs-config.js" # Instala e inicia o Browser Sync
    ports:
      - "3000:3000"
    depends_on:
      - web
