version: "3.8"

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./src/js:/usr/share/nginx/html/js
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
